#!/bin/bash

function F
{
    local y=0 # F 함수 내에서만 쓰일 수 있도록 local로 y 정의

    for i in $@ 1 # i에 $@(3 2) 1 대입됨

    do
        y=$y+$i # let이 아니므로 문자열로 y에 저장됨 0+3+2+1, = 띄어쓰지 않도록 주의
    done
    echo $y
}
F 3 $1 #함수에 매개변수로 3과 전달받은 첫번째 인자(2)를 전달함


